typography_spectrum: 0.8994766268879175
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#C3C4C6'
    - '#2A3322'
    - '#7F785E'
  brandStrength: 0.7683417375665158
  lightness: 0.4368572374805808
  saturation: 0.5064048157073557
  rhythmicContrast: 0.3937751667108387
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.8445287672802806
author:
  name: Daniel
  url: ''
  email: ''
name: The Road of Voice
url: 'https://thegrid.ai/roadofvoice'
navigation:
  - name: Portfolio
    url: 'http://portfolio.swidnikk.com'
    type: external
title: The Road of Voice
content: []
description: Days of Darkness
purpose:
  - type: contact
    url: 'mailto:da.webs@gmail.com'
    label: Send your voice upon the road.
analytics:
  twitter: swidnikk
