layout_spectrum: 0.02435945405717017
typography_spectrum: 0.4743970087294162
color:
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#C3C4C6'
    - '#2A3322'
    - '#7F785E'
  brandStrength: 0.7697672917308415
  lightness: 0.4383202688567488
  saturation: 0.5037378070663919
  rhythmicContrast: 0.39056111123320636
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics:
  twitter: swidnikk
author:
  name: Daniel
  url: ''
  email: ''
name: The Road of Voice
url: 'https://thegrid.ai/roadofvoice/'
navigation:
  - name: Portfolio
    url: 'http://portfolio.swidnikk.com'
    type: external
  - name: Tools
    id: fd6e44b6-11ab-4885-a9d5-b6fe1e906df0
    type: content
title: The Road of Voice
content: []
description: Days of Darkness
purpose:
  - type: contact
    url: 'mailto:da.webs@gmail.com'
    label: Send your voice up the road
